#ifndef	QUICKLOOTRE_VERSION_INCLUDED
#define QUICKLOOTRE_VERSION_INCLUDED

#define QUICKLOOTRE_VERSION_MAJOR		1
#define QUICKLOOTRE_VERSION_MINOR		3
#define QUICKLOOTRE_VERSION_PATCH		0
#define QUICKLOOTRE_VERSION_BETA		0
#define QUICKLOOTRE_VERSION_VERSTRING	"1, 3, 0, 0"

#endif
